# Sample AWS machine class

apiVersion: machine.sapcloud.io/v1alpha1
kind: AWSMachineClass
metadata:
  name: test-aws # Name of aws machine class goes here
  namespace: default # Namespace in which the machine class is to be deployed
spec:
  ami: ami-a4cefac1 # Amazon machine image name goes here
  region: us-east-2 # Region in which machine is to be deployed
  machineType: m4.xlarge # Type of ec2 machine
  iam:
    name: openshift_node_describe_instances # Name of the AWS Identity and Access Management
  keyName: jdiaz_key # EC2 keypair used to access ec2 machine
  networkInterfaces:
    - subnetID: subnet-c679c2ae # The subnetID in which machine is to be deployed
      securityGroupIDs: ["sg-0da63666","sg-0ea63665","sg-6ca63607"] # The security groups to which it is attached to
      associatePublicIPAddress: true
  tags:
    Name: sample-machine-name # Name tag that can be used to identify a machine at AWS
    ###kubernetes.io/cluster/cluster-name: "1" # Tag that helps a new node to join existing AWS cluster (replace cluster-name with real cluster name)
    kubernetes.io/cluster/jdiaztest: "jdiaztest" # Tag that helps a new node to join existing AWS cluster (replace cluster-name with real cluster name)
    customtag: "mycustomtag"
    tag1: tag1-value # A set of additional tags attached to a machine (optional)
    tag2: tag2-value # A set of additional tags attached to a machine (optional)
  secretRef: # Secret pointing to a secret which contains the provider secret and cloudconfig
    namespace: default  # Namespace
    name: aws-secret # Name of the secret
  blockDevices:
    - ebs:
        volumeSize: 100  # Size of the root block device
        volumeType: gp2 # Type of the root block device
    - ebs:
        volumeSize: 100
        volumeType: gp2
